name: Run UltrafastVisualTest

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Install dependencies
        run: mvn install

      - name: Run test
        run: mvn test -Dtest=com.applitools.UltrafastVisualTest
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          DEMO_SITE: original